#!/bin/bash

LOCALPATH=publish_$(date +%Y%m%d_%H%M%S)

mkdir $LOCALPATH &&\
(
  echo "Installing kernel modules to $LOCALPATH"
  INSTALL_MOD_PATH=$LOCALPATH/ make modules_install >/dev/null 2>&1 
  if [ $? -ne "0" ] ; then
    echo "Failed to install modules to $LOCALPATH"
    exit 1
  fi
) &&\

(
  echo "Installing kernel headers to $LOCALPATH"
  INSTALL_HDR_PATH=$LOCALPATH/ make headers_install >/dev/null 2>&1
  if [ $? -ne "0" ] ; then
    echo "Failed to install kernel headers to $LOCALPATH"
    exit 1
  fi
) &&\

(
  cd compat-drivers-3.8.3-2-snpu &&\
  echo "Installing external wireless modules to $LOCALPATH"
  KLIB_BUILD=`pwd`/../ ARCH=arm CROSS_COMPILE=`pwd`/../cross-toolchain/arm-fsl-linux-gnueabi/bin/arm-linux- INSTALL_MOD_PATH=$LOCALPATH/ make install-modules >/dev/null 2>&1

  if [ $? -ne "0" ] ; then
    echo "Failed to install external wireless modules to $LOCALPATH"
    exit 1
  fi
) &&\

(
  echo "Copying SPI and NAND bootstreams to $LOCALPATH"
  cp imx-bootlets-src-10.12.01/imx28_ivt_linux.s* $LOCALPATH/lib/modules/
  if [ $? -ne "0" ] ; then
    echo "Failed to failed to copy bootstream files to $LOCALPATH"
    exit 1
  fi
) &&\

(
  if [ -e arch/arm/boot/uImage ] ; then
    echo "Copying U-Boot kernel to $LOCALPATH"
    cp arch/arm/boot/uImage $LOCALPATH/boot
    if [ $? -ne "0" ] ; then
      echo "Failed to failed to copy U-Boot kernel to $LOCALPATH"
      exit 1
    fi
  else
    echo "U-Boot kernel does not exist, skipping"
  fi
)
